### ISSUE TITLE
Write Documentation for v0.0.1

### ISSUE THREAD

**Issue by jasperspahl** [LibreCuisine/LibreCuisine#17]
Writing a short introduction on how every thing works in the docs / wiki

- [ ] Add Chart from #14 
- [ ] Add Chart from #16 
- [ ] Add Chart from #10
